- packages/appcd-fswatcher/src/fswatcher.js
- packages/appcd-plugin/src/external-plugin.js
- packages/appcd-plugin/src/plugin.js
- packages/appcd-plugin/test/fixtures/good-with-ignore/index.js
- packages/appcd-plugin/test/fixtures/good-with-ignore/package.json
- packages/appcd-plugin/test/test-plugin-manager.js
https://jira.appcelerator.org/browse/DAEMON-222
- To explicitly call it out 589915b2accd6c6dce8362ac16ffe63e95604eb8 changes the FSWatcher to ignore the change event on Windows, which prevents a file written in 'adir' causing a change event on 'adir', **however** this is also preventing events such as folders being hidden, made read only from propagating through so I think the method of doing this needs to get smarter.
- Side-note that this change lowers the failures in the unit tests from 25 to 4 so at least there's something good!
- It might be good to expand upon the default in this.ignore https://github.com/ewanharris/appc-daemon/blob/81f71e735b0171f09797bd963660283c6449735e/packages/appcd-plugin/src/plugin.js#L220 to include some extra directories but I'm not sure what is best.
- I …
> [DAEMON-222] Allow plugins to register paths to be ignored

- packages/appcd-plugin/src/external-plugin.js
- packages/appcd-plugin/test/fixtures/good-with-ignore/index.js
- packages/appcd-plugin/test/fixtures/good-with-ignore/package.json
- packages/appcd-plugin/test/test-plugin-manager.js
https://jira.appcelerator.org/browse/DAEMON-234
- Spawn plugin with a cwd of its path (with test)
- Update npm deps, namely cli-kit in appcd. For some reason `gulp upgrade` wouldn't update this so I had to edit package.json directly (checking the Jenkins jobs it looks like this was a problem there too). A lot of the noise looks like churn from a registry switch in the yarn lockfiles 🤷‍♂️
> Spawn plugin with a cwd of its path, update deps

- docs/Getting-Started.md
- gulpfile.js
- packages/appcd-core/conf/default.js
- packages/appcd-core/conf/preprod.json
- packages/appcd-core/conf/prod.json
- packages/appcd-telemetry/src/telemetry.js
- packages/appcd-telemetry/test/test-telemetry.js
https://jira.appcelerator.org/browse/DAEMON-241
- Remove prod and preprod confs, merging prod into default
- Add deployType to events, setting to production if it doesn't exist
- Make gulp watch set deployType to development
> [DAEMON-241] Fix telemetry guid and add deployType to events

- packages/appcd-config/test/test-config.js
- packages/appcd-detect/src/detector.js
- packages/appcd-detect/test/test-detect-engine.js
- packages/appcd-fswatcher/package.json
- packages/appcd-fswatcher/src/fswatcher.js
- packages/appcd-fswatcher/test/after.js
- packages/appcd-fswatcher/test/restricted.js
- packages/appcd-fswatcher/test/test-fswatch-manager.js
- packages/appcd-fswatcher/test/test-fswatcher.js
- packages/appcd-gulp/src/templates/standard.js
- packages/appcd-machine-id/test/test-machine-id.js
- packages/appcd-nodejs/test/test-nodejs.js
- packages/appcd-path/test/test-path.js
- packages/appcd-plugin/test/test-plugin-manager.js
- packages/appcd-plugin/test/test-plugin-path.js
- packages/appcd-subprocess/test/test-subprocess-manager.js
- packages/appcd-telemetry/test/test-telemetry.js
[DAEMON-235] Greatly improved recursion support. Deleted directories now remove recursive children unless they are explicitly being watched. Supports recursively watching directories that were created after the fs watcher was created. Fixed bug were files were being recursively watched instead of just directories.
[DAEMON-233] Added support for permission checks. If a node is restricted, it will not be able to descend the directory tree.
Improved fs watcher code quality and docs. Unit tests are now at 98.34% on macOS.
To test, you must run `gulp coverage` on all platforms, then `sudo gulp coverage` on Linux and macOS.
> DAEMON-235 and DAEMON-233 - appcd-fswatcher improvements

- lerna.json
- package.json
- yarn.lock
After reading https://yarnpkg.com/blog/2018/02/15/nohoist/, I believe this is the correct config to keep appcd-default-plugins and it's dependencies from stomping on linked modules. This brings down the size of the repo to about 450 MB
> Reinstate yarn workspaces

- packages/appcd-fswatcher/src/fswatcher.js
https://jira.appcelerator.org/browse/DAEMON-232
* Fixed restricted directory detection.
* Fixed duplicate notifications for nested directories.
To test:
1. Create a file called `fstest.js` in the `appc-daemon\packages\appcd-fswatcher` directory:
```js
const fsw = require('./dist/index');
const renderTree = fsw.renderTree;
const FSWatcher = fsw.FSWatcher;
const watcher = new FSWatcher('C:\\Users\\chris\\Desktop', { recursive: true });
watcher.on('change', evt => {
console.log(evt);
setTimeout(() => {
console.log(renderTree());
console.log();
}, 100);
});
console.log(renderTree());
console.log();
```
2. Create a `Desktop\foo\bar` directory.
3. Run `node fstest.js`
4. In Windows Explorer, right click the `foo` directory and go to Properties, then click on the Security tab. Click the Edit …
> [DAEMON-232] Windows fswatcher fixes

- docs/Services/plugin.md
- packages/appcd-plugin/CHANGELOG.md
- packages/appcd-plugin/package.json
- packages/appcd-plugin/src/external-plugin.js
- packages/appcd-plugin/src/plugin-base.js
- packages/appcd-plugin/src/plugin-manager.js
- packages/appcd-plugin/src/plugin.js
Reset the plugin's 'stack' message when the plugin is stopped.
Fixed error handling when a plugin fails to activate or deactivate.
Added '/appcd/plugin/status/:name?/:version?' service to get a plugin's status without invoking the plugin.
Updated the plugin service docs with the status endpoint and fixed some typos.
> appcd-plugin@1.1.1

- packages/appcd-core/CHANGELOG.md
- packages/appcd-core/package.json
- packages/appcd-gulp/CHANGELOG.md
- packages/appcd-gulp/package.json
- packages/appcd-gulp/src/test-setup.js
- packages/appcd-gulp/src/test-transpile.js
- packages/appcd/CHANGELOG.md
- packages/appcd/package.json
- yarn.lock
appcd@1.1.2 and appcd-core@1.1.2 updated deps.
appcd-gulp@1.1.4 fixed deprecated sinon api and resolve parent id in transpile filename resolver.
> appcd@1.1.2 and appcd-core@1.1.2 updated deps.

- packages/appcd-core/CHANGELOG.md
- packages/appcd-core/src/server.js
- packages/appcd-util/CHANGELOG.md
- packages/appcd-util/src/util.js
- packages/appcd-util/test/test-util.js
Futureproofed use of process._getActiveHandles() and process.binding().
Replaced dependency on timer_wrap.
Added new trackTimers() function that uses async hooks.
Fixes DAEMON-268.
https://jira.appcelerator.org/browse/DAEMON-268
> fix(appcd-util): Fixed support for Node.js 11.

- packages/appcd-gulp/CHANGELOG.md
- packages/appcd-gulp/package.json
- packages/appcd-gulp/src/templates/standard.js
> chore(appcd-gulp): Added cobertura reporter when running nyc.

- packages/appcd-core/conf/default.js
- packages/appcd-telemetry/src/telemetry.js
- packages/appcd-telemetry/test/test-telemetry.js
This PR will update the telemetry formats to the latest specifications, and point to the latest endpoints. The old endpoints and formats are still accepted, but we want to move everything to the new structures to reduce complexity.
It also introduces crash reporting by sending error messages and stack traces in a `crash.report` event (which uses the internal Crash Analytics system). I'm not sure if how I wired this up is the best way for the daemon though, so open to suggestions!
> Update telemetry alongside latest specifications

- packages/appcd-plugin/CHANGELOG.md
- packages/appcd-plugin/package.json
- packages/appcd-plugin/src/tunnel-stream.js
fix: Replaced call to 'formatWithOptions()' with 'format()' so that appcd@1.x would not break on Node.js 8.11.2. (DAEMON-281)
https://jira.appcelerator.org/browse/DAEMON-281
> fix: Replaced call to 'formatWithOptions()' with 'format()'

- packages/appcd-core/CHANGELOG.md
- packages/appcd-core/package.json
- packages/appcd-core/src/server.js
- packages/appcd-default-plugins/CHANGELOG.md
- packages/appcd-default-plugins/README.md
- packages/appcd-default-plugins/index.js
- packages/appcd-default-plugins/package.json
- packages/appcd-default-plugins/postinstall.js
- packages/appcd/CHANGELOG.md
- packages/appcd/package.json
- yarn.lock
BREAKING CHANGE(appcd-default-plugins): Install plugins in appcd homeplugins dir instead of appcd-default-plugins dir.
chore(appcd-default-plugins): v3.0.0
chore(appcd-core): v2.8.0
chore(appcd): v2.7.0
Original ticket: https://jira.appcelerator.org/browse/DAEMON-280
> appcd-default-plugins permission fix

- packages/appcd-core/src/websocket-session.js
- packages/appcd-core/test/test-websocket-session.js
Sending `unsubscribe` requests from `appcd-client` fails because the `sid` is not added to the request when using websockets.
> fix(core): include sid in context from websockets

- packages/appcd/CHANGELOG.md
- packages/appcd/package.json
- packages/appcd/src/common.js
fix(common): Fixed bug where the incorrect global package directory was being resolved based on the Node.js executable used to spawn the core instead of the Node.js version used to run the 'appcd' command.
> fix: Global plugin path resolution

- packages/appcd-nodejs/CHANGELOG.md
- packages/appcd-nodejs/src/nodejs.js
- packages/appcd/CHANGELOG.md
- packages/appcd/src/common.js
fix(appcd): Re-enable detaching the core when starting the daemon to prevent unintended SIGINT propagation. [DAEMON-288]
fix(appcd-nodejs): Discontinue automatic unref of detached subprocesses.
https://jira.appcelerator.org/browse/DAEMON-288
> fix: Detached core process [DAEMON-288]

- packages/appcd-gulp/CHANGELOG.md
- packages/appcd-gulp/src/test-transpile.js
- packages/appcd-nodejs/CHANGELOG.md
- packages/appcd-nodejs/src/nodejs.js
- packages/appcd-plugin/CHANGELOG.md
- packages/appcd-plugin/src/plugin-module.js
- packages/appcd-plugin/test/fixtures/require-api.js
- packages/appcd-plugin/test/test-plugin-module.js
- packages/appcd-response/CHANGELOG.md
- packages/appcd-response/package.json
- packages/appcd-response/src/locale.js
- packages/appcd/CHANGELOG.md
- packages/appcd/src/common.js
Fix `require` compatibility in plugin modules.
- Add `require.resolve.paths`
- Add `require.main`
> fix(plugin): require API compatibility

- packages/appcd-default-plugins/CHANGELOG.md
- packages/appcd-default-plugins/package.json
- packages/appcd-default-plugins/src/index.js
For some reason, on Windows, an overwritten PATH in the environment variables is not properly inherited when calling spawn(), however if we override the environment variables for the current process, they are properly inherited. This could be just a Node 10 issue.
JIRA: https://jira.appcelerator.org/browse/DAEMON-330
> Yarn not found during plugin install at startup

- package.json
- packages/appcd-client/package.json
- packages/appcd-core/CHANGELOG.md
- packages/appcd-core/package.json
- packages/appcd-core/src/websocket-session.js
- packages/appcd-gulp/package.json
- packages/appcd-http/package.json
- packages/appcd-plugin/CHANGELOG.md
- packages/appcd-plugin/src/external-plugin.js
- packages/appcd-plugin/src/helpers.js
- packages/appcd-plugin/src/plugin.js
- packages/appcd-plugin/src/tunnel.js
- packages/appcd-plugin/test/test-plugin.js
- packages/appcd-request/src/request.js
- packages/appcd-telemetry/src/telemetry.js
- packages/appcd/src/commands/config.js
- test/test-appcd-config.js
- test/test-plugin-windows.js
- yarn.lock
fix(appcd-plugin): Fixed bug where an 'inactivityTimeout' of zero would be tested as falsey and fallback to the default inactivity timeout.
fix(appcd-plugin): Fixed bug where error details were not being passed back when an internal plugin-to-plugin call threw an error.
chore(appcd-core): Bumped Node.js version to 12.16.3.
> Small bug fixes

- packages/appcd-gulp/package.json
- packages/appcd-plugin/CHANGELOG.md
- packages/appcd-plugin/src/plugin-base.js
- packages/appcd/CHANGELOG.md
- packages/appcd/package.json
- packages/appcd/src/commands/status.js
- yarn.lock
feat(appcd:status): Added plugin 'uptime' column to list of plugins.
refactor(appcd:status): Removed plugin 'type' column from list of plugins.
refactor(appcd:status): Replace user's home directory references in plugin and subprocess paths with '~'.
feat(plugin): Added plugin start time to the plugin info.
feat(plugin): Added 'appcd.logger' for plugins to create new namespaced loggers.
> appcd status output cleanup

- gulpfile.js
Yarn includes npm, probably for compat reasons,
yarn UA example -> yarn/1.22.5 npm/? node/v14.13.1 darwin x64
npm UA example -> npm/6.14.8 node/v14.13.1 darwin x64
> build: fix user agent check

- docs/Environment Variables.md
- packages/appcd/scripts/postinstall.js
Allowing set a `APPCD_SKIP_POSTINSTALL` environment variable to stop the postinstall script in appcd being ran, this will be used by the appc cli when performing an npm rebuild when switching node versions
> feat: allow disabling appcd postinstall script

- packages/appcd-util/src/util.js
The HOME env var is not always set on Windows, so it would be set to undefined, causing the redcation
to ultimately blow up
Disclaimer, I have not run the tests because that's just the life I lead (jk, I just can't figure out how to just run appc-util's tests)
> fix(util): use os.homedir for users home directory

- packages/appcd-util/CHANGELOG.md
- packages/appcd-util/src/util.js
- packages/appcd-util/test/test-util.js
fix(util:makeSerializable): Only ignore nested duplicates that form circular references instead of anything that is a duplicate.
JIRA: https://jira.appcelerator.org/browse/DAEMON-342
> [DAEMON-342] Fix circular ref removal

- packages/appcd-gulp/CHANGELOG.md
- packages/appcd-gulp/src/test-runner.js
- packages/appcd-gulp/src/test-transpile.js
* feat(test): Exposed Mocha 'slow' and 'timeout' parameters in test runner.
* fix(coverage): Simplified coverage file resolution by letting Node's module system find the module first, then switch the resolved filename from the 'dist' version to the 'src' version if the file is apart of the package being tested.
> appcd-gulp test coverage improvements

- packages/appcd-fs/CHANGELOG.md
- packages/appcd-fs/package.json
- packages/appcd-fs/src/fs.js
- packages/appcd-fs/test/test-fs.js
* feat(appcd-fs): Added 'mkdirpSync()', 'moveSync()', and 'writeFileSync()' helpers that create parent directories and apply parent directory ownership.
* chore(appcd-fs): Updated dependencies.
> appcd-fs@2.1.0
