packages/appcd-util/src/util.js
packages/appcd-util/test/test-util.js

https://jira.appcelerator.org/browse/DAEMON-238

[DAEMON-238] Added the ability to cancel a pending debounce.

---

Jenkinsfile
packages/appcd-plugin/test/test-plugin-manager.js

Attempting to get Jenkins back green, reviewing locally I believe this could just be a timeout issue and nothing more sinister.
Currently tying the test to linux nodes, will run multiple jobs on linux, then tie to osx nodes and run multiple jobs there to hopefully show any failures

Bump timeout for tests

---

Jenkinsfile
packages/appcd-plugin/test/test-plugin-manager.js

Reverts appcelerator/appc-daemon#285

Revert "Bump timeout for tests"

---

packages/appcd-plugin/test/test-plugin-manager.js
packages/appcd-subprocess/test/fixtures/ipc.js

This made me go from 3 failures in 100 tries to 0 failures. Probably just a coincidence

More test timeout bumps/fixes

---

CHANGELOG.md

https://jira.appcelerator.org/browse/DAEMON-237

[DAEMON-237] Added a changelog with 1.0.1 and 1.1.0 changes.

---

gulpfile.js
packages/appcd-core/package.json
packages/appcd/package.json
yarn.lock

https://jira.appcelerator.org/browse/DAEMON-242

[DAEMON-242] Updated to cli-kit@0.0.12.

---

packages/appcd-plugin/test/test-plugin-manager.js

Remove only

---

docs/Architecture-Overview.md
docs/Components/Plugin-System.md
packages/appcd-core/conf/default.js
packages/appcd-core/package.json
packages/appcd-core/src/server.js
packages/appcd-nodejs/src/nodejs.js
packages/appcd-nodejs/test/test-nodejs.js
packages/appcd-plugin/src/plugin.js
packages/appcd-util/src/util.js
packages/appcd/src/common.js

https://jira.appcelerator.org/browse/DAEMON-244

[DAEMON-244] Implemented purging unused Node.js executabes

---

packages/appcd-client/src/client.js
packages/appcd-client/test/test-client.js
packages/appcd-core/src/status-monitor.js
packages/appcd-core/test/test-status-monitor.js

https://jira.appcelerator.org/browse/DAEMON-248

[DAEMON-248] Fixed broken unit tests.

---

packages/appcd/CHANGELOG.md
packages/appcd/package.json
packages/appcd/src/exec.js

Changed 'exec' command to return full JSON response instead of just the message.

appcd@1.1.1

---

packages/appcd-config/CHANGELOG.md
packages/appcd-config/package.json
packages/appcd-dispatcher/CHANGELOG.md
packages/appcd-dispatcher/package.json
packages/appcd-fs/CHANGELOG.md
packages/appcd-fs/package.json
packages/appcd-gulp/CHANGELOG.md
packages/appcd-logger/CHANGELOG.md
packages/appcd-logger/package.json
packages/appcd-nodejs/CHANGELOG.md
packages/appcd-nodejs/package.json
packages/appcd-path/CHANGELOG.md
packages/appcd-path/package.json
packages/appcd-request/CHANGELOG.md
packages/appcd-request/package.json
packages/appcd-response/package.json
packages/appcd-subprocess/CHANGELOG.md
packages/appcd-subprocess/package.json
packages/appcd-util/CHANGELOG.md
packages/appcd-util/package.json
packages/appcd-winreg/CHANGELOG.md
packages/appcd-winreg/package.json
yarn.lock

appcd-config@1.1.2
appcd-dispatcher@1.2.0
appcd-fs@1.1.3
appcd-logger@1.1.2
appcd-nodejs@1.1.2
appcd-path@1.1.2
appcd-request@1.1.2
appcd-response@1.1.3
appcd-subprocess@1.1.2
appcd-util@1.1.2
appcd-winreg@1.1.2

Published several appcd packages:

---

packages/appcd-core/CHANGELOG.md
packages/appcd-core/src/server.js
packages/appcd/src/commands/dump.js

https://jira.appcelerator.org/browse/DAEMON-263

[DAEMON-263] Added AMPLIFY_CLI env var to the telemetry payload and dump data.

---

packages/appcd-fs/src/fs.js
packages/appcd-fs/test/test-fs.js
yarn.lock

We can use this in places where we now do some hacky handling around scoped packages (namely amplify-cli and somewhere in the daemon)

Add readdirScoped function

---

packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/src/external-plugin.js
packages/appcd-plugin/src/plugin-base.js

https://jira.appcelerator.org/browse/DAEMON-265

[DAEMON-265] Added a plugin's list of services to the plugin info.

---

packages/appcd-subprocess/package.json
yarn.lock

Which pegs to event-stream=3.3.4 - fixing security issue/bitcoin exploit in event-stream@3.3.6
https://github.com/dominictarr/event-stream/issues/116

fix(security): Peg to ps-tree@^1.1.1

---

packages/appcd/CHANGELOG.md
packages/appcd/src/commands/config.js

Fixes DAEMON-269.
https://jira.appcelerator.org/browse/DAEMON-269

fix(config): Actions were not being translated correctly when dispatching request to daemon config service.

---

gulpfile.js
package.json
packages/appcd-dispatcher/CHANGELOG.md
packages/appcd-dispatcher/package.json
packages/appcd-dispatcher/src/dispatcher.js
packages/appcd-dispatcher/test/test-dispatcher.js
packages/appcd-logger/CHANGELOG.md
yarn.lock

https://jira.appcelerator.org/browse/DAEMON-271

[DAEMON-271] Dispatcher object response fixes.

---

packages/appcd-subprocess/CHANGELOG.md
packages/appcd-subprocess/src/subprocess-manager.js
packages/appcd-subprocess/test/test-subprocess-manager.js

https://jira.appcelerator.org/browse/DAEMON-272

fix(subprocess): Removed broken and useless 'http' source restriction.

---

packages/appcd-client/CHANGELOG.md
packages/appcd-client/package.json
packages/appcd-client/src/client.js

fix: Fixed unhandled exception when attempting to spawn the Appc Daemon.

---

packages/appcd-client/CHANGELOG.md
packages/appcd-client/package.json
yarn.lock

fix(appcd-client): Fixed bad 'appcd-response' dependency version.

---

packages/appcd-core/CHANGELOG.md
packages/appcd-core/package.json
packages/appcd/CHANGELOG.md
packages/appcd/package.json
packages/appcd/src/commands/config.js

fix(appcd): Fixed bug where bad 'config' command would not disconnect from daemon.
chore(appcd-core): Updated to appcd-config-service@2.0.0.
chore(appcd): Updated to appcd-core@2.7.0.
chore(appcd-core): v2.7.0
chore(appcd): v2.6.0

Bug fix and npm updates

---

gulpfile.js
packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/package.json
yarn.lock

chore(gulp): Added ci-clean task that will do a destructive clean for CI builds.
chore(gulp): Changed upgrade task to only update package.json deps when -u is specified.

gulp improvements

---

packages/appcd-default-plugins/CHANGELOG.md
packages/appcd-default-plugins/package.json

chore(default-plugins): Updated plugins to latest appcd v3 compatible versions.

chore(default-plugins): v4.1.0

---

README.md
gulpfile.js
lerna.json
package.json
packages/appcd-core/CHANGELOG.md
packages/appcd-core/package.json
packages/appcd-default-plugins/CHANGELOG.md
packages/appcd-default-plugins/package.json
packages/appcd-http/CHANGELOG.md
packages/appcd-http/package.json
packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/package.json
yarn.lock

chore: Updated readme.
chore: Added plugins to lerna.
feat: Added ability to 'appcd stop' the daemon when being run as 'gulp watch'.
chore: Updated dependencies.
feat: Added 'gulp link-plugins' and 'gulp unlink-plugins' to top-level gulpfile.

Adding plugins and maintenance

---

Jenkinsfile
gulpfile.js
packages/appcd-config/CHANGELOG.md
packages/appcd-config/src/config.js
packages/appcd-config/src/index.js
packages/appcd-config/test/fixtures/good-readonly.js
packages/appcd-config/test/test-config.js
packages/appcd-gulp/package.json
packages/appcd-gulp/src/test-runner.js
packages/appcd-gulp/src/test-transpile.js
packages/appcd/CHANGELOG.md
packages/appcd/src/common.js
test/common.js
test/test-appcd-config.js
yarn.lock

test: Wired up top-level coverage tests for everything.
fix(config): Fixed bug introduced with config layer feature that wasn't allowing readonly values to be overwritten during initial load.
fix(appcd):  Fixed bug with order of loading an arbitrary  and the user-defined config file.

Coverage test tasks

---

docs/Components/Configuration-System.md
packages/appcd-gulp/package.json
packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/package.json
packages/appcd-plugin/src/plugin.js
test/test-plugin-android.js
yarn.lock

docs(config): Added namespace description to config docs.
feat(plugins): Added 'dependencies' to plugin info.
chore(android): Removed debug output.
test(android): Added support for Android v1 plugin to test.

Bug fixes, cleanup, updates, and plugin info.

---

packages/appcd-default-plugins/src/index.js
packages/appcd-telemetry/src/telemetry.js

JIRA: https://jira.appcelerator.org/browse/DAEMON-284
These are the fixes i made locally to fix offline support. There may be other issues that i didn't notice but these ones were blocking me.

fix: improve offline support in telemetry and default plugins

---

packages/appcd-plugin/src/external-plugin.js
packages/appcd-plugin/src/tunnel.js

JIRA: https://jira.appcelerator.org/browse/DAEMON-285
Service subscriptions are cleaned up after a client disconnects based on this line in the service dispatcher:
https://github.com/appcelerator/appc-daemon/blob/fe3b899d5f69c66e9d5bb2eaeb8370bd5fd72bb1/packages/appcd-dispatcher/src/service-dispatcher.js#L184
However, this doesn't handle the case that in external plugins this is the response stream of the tunnel to the parent process, so `end` is never called in that particular scenario.
The fix to this is to listen for the response stream `end` event in the plugin's parent process and then issue a manual `unsubscribe` to the external plugin via the tunnel. 
@cb1kenobi i'm not quite sure if there are other responses other the subscriptions that can be a stream? If so then there might be …

fix(plugin): unsubscribe from external plugin services on client close

---

packages/appcd-core/CHANGELOG.md
packages/appcd-core/src/server.js

JIRA: https://jira.appcelerator.org/browse/DAEMON-308

fix(appcd-core): Await PluginManager to initialize.

---

packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/src/plugin.js
packages/appcd-plugin/test/fixtures/wrong-api-ver/package.json
packages/appcd-plugin/test/test-plugin.js

JIRA: https://jira.appcelerator.org/browse/DAEMON-309

feat(appcd-plugin): Added support for 'apiVersion' in plugin's package.json

---

docs/Release Notes/Appc Daemon 1.0.0.md
docs/Release Notes/Appc Daemon 1.0.1.md
docs/Release Notes/Appc Daemon 1.1.0.md
docs/Release Notes/Appc Daemon 1.1.1.md
docs/Release Notes/Appc Daemon 1.1.2.md
docs/Release Notes/Appc Daemon 1.1.3.md
docs/Release Notes/Appc Daemon 2.0.0.md
docs/Release Notes/Appc Daemon 2.0.1.md
docs/Release Notes/Appc Daemon 2.1.0.md
docs/Release Notes/Appc Daemon 2.2.0.md
docs/Release Notes/Appc Daemon 2.3.0.md
docs/Release Notes/Appc Daemon 2.4.0.md
docs/Release Notes/Appc Daemon 2.5.0.md
docs/Release Notes/Appc Daemon 2.6.0.md
docs/Release Notes/Appc Daemon 2.7.0.md
docs/Release Notes/Appc Daemon 3.0.0.md
docs/Release Notes/Appc Daemon 3.1.0.md
docs/Release Notes/Appc Daemon 3.2.0.md
gulpfile.js
package.json

feat: Add release notes generator.
chore: Generate appcd release notes.
JIRA: https://jira.appcelerator.org/browse/DAEMON-316

Appc Daemon release notes!!!

---

docs/Releases.md

https://jira.appcelerator.org/browse/DAEMON-315

doc: Adding releases index.

---

packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/src/plugin-api-version.js
packages/appcd-plugin/src/plugin-base.js
packages/appcd-plugin/src/plugin-manager.js
packages/appcd-plugin/src/plugin.js
packages/appcd/CHANGELOG.md
packages/appcd/src/commands/status.js

JIRA: https://jira.appcelerator.org/browse/DAEMON-314

feat: Added Plugin API Version to the status output. Fixes DAEMON-314.

---

packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/src/plugin-manager.js

JIRA: https://jira.appcelerator.org/browse/DAEMON-328

fix(appcd-plugin): Sort plugins when getting status. Fixes DAEMON-328.

---

packages/appcd-default-plugins/CHANGELOG.md
packages/appcd-default-plugins/package.json
packages/appcd-default-plugins/src/index.js
yarn.lock

fix(appcd-default-plugins): Create missing 'lerna.cmd' and 'yarn.cmd' scripts needed for Windows. Fixes DAEMON-332.
JIRA: https://jira.appcelerator.org/browse/DAEMON-332

[DAEMON-332] Create missing 'lerna.cmd' and 'yarn.cmd' scripts

---

docs/Releases.md
packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/README.md
packages/appcd-plugin/package.json
packages/appcd-plugin/src/plugin-api-version.js
yarn.lock

JIRA: https://jira.appcelerator.org/browse/DAEMON-277

BREAKING CHANGE(appcd-plugin): Removed 'appcd-winreg'.

---

packages/appcd-core/CHANGELOG.md
packages/appcd-core/src/server.js

JIRA: https://jira.appcelerator.org/browse/DAEMON-313

refactor(appcd-core): Removed Titanium CLI Genymotion config import.

---

docs/Components/Plugin-System.md
packages/appcd-config-service/src/config-service.js
packages/appcd-core/package.json
packages/appcd-dispatcher/src/data-service-dispatcher.js
packages/appcd-gulp/package.json
packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/src/external-plugin.js
packages/appcd-plugin/src/plugin-manager.js
packages/appcd-plugin/src/plugin.js
packages/appcd/package.json
packages/appcd/src/commands/status.js
yarn.lock

feat(appcd-plugin): Added support for a 'autoStart' flag in the plugin's 'package.json'.
fix(appcd): Fixed coloring of plugin errors in status command output.

Plugin auto-start, appcd status color fix, updated deps

---

packages/appcd-core/package.json
packages/appcd-plugin/CHANGELOG.md
packages/appcd-plugin/src/external-plugin.js
packages/appcd-plugin/src/tunnel-stream.js
packages/appcd/package.json
yarn.lock

feat(appcd-plugin): Redact specific sensitive data from plugin debug logging.

Redact sensitive data in debug log, updated deps

---

packages/appcd-core/package.json
packages/appcd/CHANGELOG.md
packages/appcd/package.json
packages/appcd/src/commands/status.js
yarn.lock

feat(appcd:status): Added 'health' section to status output.

---

docs/Release Notes/Appc Daemon 4.0.0.md
gulpfile.js
packages/appcd-core/package.json
packages/appcd-gulp/package.json
packages/appcd-plugin/src/tunnel-stream.js
packages/appcd/CHANGELOG.md
packages/appcd/package.json
packages/appcd/src/commands/pm.js
packages/appcd/src/commands/pm/list.js
packages/appcd/src/commands/pm/search.js
packages/appcd/src/commands/pm/update.js
packages/appcd/src/commands/status.js
packages/appcd/src/common.js
yarn.lock

doc: Cleaned up changelogs.
chore: Updated deps.
style(appcd): Cleaned up CLI table formatting.

Docs, styling, and dep updates

---

package.json
packages/appcd-core/package.json
packages/appcd-gulp/package.json
packages/appcd/package.json
packages/appcd/src/commands/config.js
packages/appcd/src/commands/logcat.js
packages/appcd/src/main.js
yarn.lock

fix(appcd): Removed disabling showHelpOnError as it's now disabled.

---

package.json
packages/appcd-core/package.json
packages/appcd/package.json
packages/appcd/src/commands/status.js
packages/appcd/src/common.js
yarn.lock

fix(appcd): Fixed style output from status command.

---

packages/appcd-gulp/package.json
packages/appcd-util/src/util.js
packages/appcd-util/test/test-util.js
yarn.lock

fix(util): Fixed date object bug in 'makeSerializable()'.

---

package.json
packages/appcd-nodejs/package.json
packages/appcd-telemetry/src/telemetry.js
yarn.lock

fix(telemetry): Fixed bug with events not being sent until shutdown.

chore: Updated deps.

---

packages/appcd-gulp/package.json
packages/appcd-util/CHANGELOG.md
packages/appcd-util/src/util.js
packages/appcd-util/test/test-util.js
yarn.lock

fix(util:sha1): Treat buffers like strings and don't JSON.stringify them.
chore: Updated deps.

Small updates
